/*
** Generated by X-Designer 
*/

/*
**LIBS: -lXm -lXmt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>




create_widget0( parent )
Widget parent;
{
	Display *display = XtDisplay ( parent );
	Widget children[14];      /* Children to manage */
	Arg al[64];           /* Arg List */
	register int ac = 0;      /* Arg Count */
	char from_s [256];    /* For font list conversion */
	XrmValue from_value, to_value; /* ditto */
	int fg, bg;           /* colour values for pixmaps */ 
	int h_spacing, v_spacing; /* default spacing for forms */ 
	XmString *list_items; /* For list items */
	int list_item;        /* Index for list_items */
	XmString xmstrings[10];    /* temporary storage for XmStrings */
	Widget widget0;
	Widget widget1;
	Widget widget2;
	Widget widget17;
	Widget widget18;
	Widget widget4;
	Widget widget5;
	Widget widget6;
	Widget widget7;
	Widget widget8;
	Widget widget9;
	Widget widget10;
	Widget widget11;
	Widget widget12;
	Widget widget13;
	Widget widget14;
	Widget widget15;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	widget0 = XmCreateDialogShell ( parent, "widget0", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNshadowType, XmSHADOW_OUT); ac++;
	widget1 = XmCreateFrame ( widget0, "debuggerPanel", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNspacing, 0); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
	XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
	widget2 = XmCreateRowColumn ( widget1, "panel", al, ac );
	ac = 0;
	widget17 = XmCreateLabel ( widget2, "target", al, ac );
	widget18 = XmCreatePushButton ( widget2, "start", al, ac );
	widget4 = XmCreatePushButton ( widget2, "run", al, ac );
	widget5 = XmCreatePushButton ( widget2, "stop", al, ac );
	widget6 = XmCreatePushButton ( widget2, "continue", al, ac );
	widget7 = XmCreatePushButton ( widget2, "step", al, ac );
	widget8 = XmCreatePushButton ( widget2, "next", al, ac );
	widget9 = XmCreatePushButton ( widget2, "finish", al, ac );
	widget10 = XmCreatePushButton ( widget2, "backtrace", al, ac );
	widget11 = XmCreatePushButton ( widget2, "up", al, ac );
	widget12 = XmCreatePushButton ( widget2, "frame", al, ac );
	widget13 = XmCreatePushButton ( widget2, "down", al, ac );
	widget14 = XmCreatePushButton ( widget2, "print", al, ac );
	widget15 = XmCreatePushButton ( widget2, "printStar", al, ac );
	children[ac++] = widget17;
	children[ac++] = widget18;
	children[ac++] = widget4;
	children[ac++] = widget5;
	children[ac++] = widget6;
	children[ac++] = widget7;
	children[ac++] = widget8;
	children[ac++] = widget9;
	children[ac++] = widget10;
	children[ac++] = widget11;
	children[ac++] = widget12;
	children[ac++] = widget13;
	children[ac++] = widget14;
	children[ac++] = widget15;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget2;
	XtManageChildren(children, ac);
	ac = 0;
}


