
/*
** Generated by X-Designer 
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Separator.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>
#include <Xm/ToggleBG.h>


Widget button1;


create_widget0( parent )
Widget parent;
{
	Display *display = XtDisplay ( parent );
	Widget children[12];      /* Children to manage */
	Arg al[64];           /* Arg List */
	register int ac = 0;      /* Arg Count */
	char from_s [256];    /* For font list conversion */
	XrmValue from_value, to_value; /* ditto */
	int fg, bg;           /* colour values for pixmaps */ 
	XmString *list_items; /* For list items */
	int list_item;        /* Index for list_items */
	XmString xmstrings[15];    /* temporary storage for XmStrings */
	Widget widget0;
	Widget widget1;
	Widget widget2;
	Widget widget3;
	Widget widget4;
	Widget widget6;
	Widget widget7;
	Widget widget8;
	Widget widget9;
	Widget widget10;
	Widget widget11;
	Widget widget12;
	Widget widget13;
	Widget widget14;
	Widget widget15;
	Widget widget16;
	Widget widget17;
	Widget widget18;
	Widget widget19;
	Widget widget20;
	Widget widget21;
	Widget widget22;
	Widget widget23;
	Widget widget24;
	Widget widget25;
	Widget widget26;
	Widget widget27;
	Widget widget28;
	Widget widget29;
	Widget widget30;
	Widget widget31;
	Widget widget32;
	Widget widget33;
	Widget widget34;
	Widget widget35;
	Widget widget36;
	Widget widget37;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	widget0 = XmCreateDialogShell ( parent, "dialog", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	widget1 = XmCreateForm ( widget0, "editModeDialog", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
	widget2 = XmCreateLabel ( widget1, "message", al, ac );
	ac = 0;
	widget3 = XmCreateLabel ( widget1, "iconSeparator", al, ac );
	XtSetArg(al[ac], XmNnumColumns, 5); ac++;
	XtSetArg(al[ac], XmNspacing, 13); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	XtSetArg(al[ac], XmNpacking, XmPACK_COLUMN); ac++;
	XtSetArg(al[ac], XmNentryAlignment, XmALIGNMENT_CENTER); ac++;
	XtSetArg(al[ac], XmNadjustLast, FALSE); ac++;
	XtSetArg(al[ac], XmNisAligned, TRUE); ac++;
	widget4 = XmCreateRowColumn ( widget1, "row", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNdefaultButtonShadowThickness, 1); ac++;
	button1 = XmCreatePushButton ( widget4, "button1", al, ac );
	ac = 0;
	widget6 = XmCreatePushButton ( widget4, "button2", al, ac );
	XtSetArg(al[ac], XmNmappedWhenManaged, FALSE); ac++;
	widget7 = XmCreatePushButton ( widget4, "separator_button", al, ac );
	ac = 0;
	widget8 = XmCreatePushButton ( widget4, "button3", al, ac );
	widget9 = XmCreateSeparator ( widget1, "widget9", al, ac );
	widget10 = XmCreateLabel ( widget1, "externalLabel", al, ac );
	widget11 = XmCreateFrame ( widget1, "widget11", al, ac );
	XtSetArg(al[ac], XmNspacing, 3); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 3); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 3); ac++;
	XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
	widget12 = XmCreateRowColumn ( widget11, "widget12", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNnumColumns, 1); ac++;
	XtSetArg(al[ac], XmNspacing, 0); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
	XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
	XtSetArg(al[ac], XmNpacking, XmPACK_TIGHT); ac++;
	widget13 = XmCreateRadioBox ( widget12, "externalBox", al, ac );
	ac = 0;
	widget14 = XmCreateToggleButtonGadget ( widget13, "externalEmacs", al, ac );
	widget15 = XmCreateToggleButtonGadget ( widget13, "externalViXterm", al, ac );
	widget16 = XmCreateToggleButtonGadget ( widget13, "externalViCmdtool", al, ac );
	widget17 = XmCreateToggleButtonGadget ( widget13, "externalOther", al, ac );
	XtSetArg(al[ac], XmNcolumns, 30); ac++;
	widget18 = XmCreateTextField ( widget12, "otherText", al, ac );
	ac = 0;
	widget19 = XmCreateLabel ( widget1, "viewLabel", al, ac );
	widget20 = XmCreateFrame ( widget1, "widget20", al, ac );
	XtSetArg(al[ac], XmNnumColumns, 1); ac++;
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	widget21 = XmCreateRadioBox ( widget20, "viewBox", al, ac );
	ac = 0;
	widget22 = XmCreateToggleButtonGadget ( widget21, "emacsView", al, ac );
	widget23 = XmCreateToggleButtonGadget ( widget21, "viView", al, ac );
	widget24 = XmCreateToggleButtonGadget ( widget21, "lessView", al, ac );
	widget25 = XmCreateLabel ( widget1, "editLabel", al, ac );
	widget26 = XmCreateFrame ( widget1, "widget26", al, ac );
	XtSetArg(al[ac], XmNnumColumns, 1); ac++;
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	widget27 = XmCreateRadioBox ( widget26, "editBox", al, ac );
	ac = 0;
	widget28 = XmCreateToggleButtonGadget ( widget27, "editEmacs", al, ac );
	widget29 = XmCreateToggleButtonGadget ( widget27, "editVi", al, ac );
	widget30 = XmCreateLabel ( widget1, "windowLabel", al, ac );
	XtSetArg(al[ac], XmNspacing, 0); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
	widget31 = XmCreateRowColumn ( widget1, "widget31", al, ac );
	ac = 0;
	widget32 = XmCreateFrame ( widget31, "widget32", al, ac );
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	widget33 = XmCreateRadioBox ( widget32, "windowBox", al, ac );
	ac = 0;
	widget34 = XmCreateToggleButtonGadget ( widget33, "windowOne", al, ac );
	widget35 = XmCreateToggleButtonGadget ( widget33, "windowSeveral", al, ac );
	widget36 = XmCreateToggleButtonGadget ( widget33, "windowMany", al, ac );
	widget37 = XmCreateToggleButton ( widget31, "splitScreens", al, ac );
	XtSetArg(al[ac], XmNdefaultButton, button1); ac++;
	XtSetValues ( widget1,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget10); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget2,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget9); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 4); ac++;
        XtSetValues ( widget3,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget4,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget4); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 0); ac++;
        XtSetValues ( widget9,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget11); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget11); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget10,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget30); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget11,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget20); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget20); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget19,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget26); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget20,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget26); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget26); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget25,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget31); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
	XtSetArg(al[ac], XmNleftPosition, 29); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget26,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget31); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget31); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget30,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget9); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
	XtSetArg(al[ac], XmNleftPosition, 56); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget31,al, ac );
	ac = 0;
	children[ac++] = button1;
	children[ac++] = widget6;
	children[ac++] = widget7;
	children[ac++] = widget8;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget14;
	children[ac++] = widget15;
	children[ac++] = widget16;
	children[ac++] = widget17;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget13;
	children[ac++] = widget18;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget12;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget22;
	children[ac++] = widget23;
	children[ac++] = widget24;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget21;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget28;
	children[ac++] = widget29;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget27;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget34;
	children[ac++] = widget35;
	children[ac++] = widget36;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget33;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget32;
	children[ac++] = widget37;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget2;
	children[ac++] = widget3;
	children[ac++] = widget4;
	children[ac++] = widget9;
	children[ac++] = widget10;
	children[ac++] = widget11;
	children[ac++] = widget19;
	children[ac++] = widget20;
	children[ac++] = widget25;
	children[ac++] = widget26;
	children[ac++] = widget30;
	children[ac++] = widget31;
	XtManageChildren(children, ac);
	ac = 0;
}


