
/*
** Generated by X-Designer 
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Separator.h>
#include <Xm/ToggleB.h>
#include <Xm/ToggleBG.h>


Widget button1;


create_widget0( parent )
Widget parent;
{
	Display *display = XtDisplay ( parent );
	Widget children[10];      /* Children to manage */
	Arg al[64];           /* Arg List */
	register int ac = 0;      /* Arg Count */
	char from_s [256];    /* For font list conversion */
	XrmValue from_value, to_value; /* ditto */
	int fg, bg;           /* colour values for pixmaps */ 
	XmString *list_items; /* For list items */
	int list_item;        /* Index for list_items */
	XmString xmstrings[15];    /* temporary storage for XmStrings */
	Widget widget0;
	Widget widget1;
	Widget widget2;
	Widget widget4;
	Widget widget5;
	Widget widget6;
	Widget widget7;
	Widget widget8;
	Widget widget9;
	Widget widget10;
	Widget widget11;
	Widget widget12;
	Widget widget13;
	Widget widget14;
	Widget widget15;
	Widget widget16;
	Widget widget17;
	Widget widget18;
	Widget widget19;
	Widget widget20;
	Widget widget21;
	Widget widget22;
	Widget widget23;
	Widget widget24;
	Widget widget25;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	widget0 = XmCreateDialogShell ( parent, "dialog", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	widget1 = XmCreateForm ( widget0, "projectDisplayDialog", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNspacing, 13); ac++;
	XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
	XtSetArg(al[ac], XmNpacking, XmPACK_COLUMN); ac++;
	XtSetArg(al[ac], XmNentryAlignment, XmALIGNMENT_CENTER); ac++;
	XtSetArg(al[ac], XmNadjustLast, FALSE); ac++;
	XtSetArg(al[ac], XmNisAligned, TRUE); ac++;
	widget2 = XmCreateRowColumn ( widget1, "row", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNdefaultButtonShadowThickness, 1); ac++;
	button1 = XmCreatePushButton ( widget2, "button1", al, ac );
	ac = 0;
	widget4 = XmCreatePushButton ( widget2, "button2", al, ac );
	XtSetArg(al[ac], XmNmappedWhenManaged, FALSE); ac++;
	widget5 = XmCreatePushButton ( widget2, "separator_button", al, ac );
	ac = 0;
	widget6 = XmCreatePushButton ( widget2, "button3", al, ac );
	widget7 = XmCreateSeparator ( widget1, "widget7", al, ac );
	XtSetArg(al[ac], XmNlabelType, XmPIXMAP); ac++;
	widget8 = XmCreateLabel ( widget1, "dbox-question", al, ac );
	ac = 0;
	widget9 = XmCreateLabel ( widget1, "groupLabel", al, ac );
	widget10 = XmCreateFrame ( widget1, "widget10", al, ac );
	widget11 = XmCreateRadioBox ( widget10, "groupBox", al, ac );
	widget12 = XmCreateToggleButtonGadget ( widget11, "groupType", al, ac );
	widget13 = XmCreateToggleButtonGadget ( widget11, "groupDirectory", al, ac );
	widget14 = XmCreateLabel ( widget1, "showLabel", al, ac );
	widget15 = XmCreateFrame ( widget1, "widget15", al, ac );
	widget16 = XmCreateRowColumn ( widget15, "widget16", al, ac );
	widget17 = XmCreateToggleButton ( widget16, "showHeaders", al, ac );
	widget18 = XmCreateToggleButton ( widget16, "showSources", al, ac );
	widget19 = XmCreateToggleButton ( widget16, "showOthers", al, ac );
	widget20 = XmCreateLabel ( widget1, "fileSetLabel", al, ac );
	widget21 = XmCreateFrame ( widget1, "widget21", al, ac );
	widget22 = XmCreateRadioBox ( widget21, "fileSetBox", al, ac );
	widget23 = XmCreateToggleButtonGadget ( widget22, "fileSetOwn", al, ac );
	widget24 = XmCreateToggleButtonGadget ( widget22, "fileSetUsed", al, ac );
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
	widget25 = XmCreateLabel ( widget1, "message", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNdefaultButton, button1); ac++;
	XtSetValues ( widget1,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget2,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget2); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 0); ac++;
        XtSetValues ( widget7,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget8,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget10); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget10); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget9,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget21); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget21); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget10,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget15); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget15); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget14,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget7); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget8); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget15,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -6); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget21); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 6); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget21); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget20,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget15); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget15); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget21,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget14); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget8); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget25,al, ac );
	ac = 0;
	children[ac++] = button1;
	children[ac++] = widget4;
	children[ac++] = widget5;
	children[ac++] = widget6;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget12;
	children[ac++] = widget13;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget11;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget17;
	children[ac++] = widget18;
	children[ac++] = widget19;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget16;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget23;
	children[ac++] = widget24;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget22;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget2;
	children[ac++] = widget7;
	children[ac++] = widget8;
	children[ac++] = widget9;
	children[ac++] = widget10;
	children[ac++] = widget14;
	children[ac++] = widget15;
	children[ac++] = widget20;
	children[ac++] = widget21;
	children[ac++] = widget25;
	XtManageChildren(children, ac);
	ac = 0;
}


