
/*
** Generated by X-Designer 
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrollBar.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleBG.h>


Widget button1;


create_widget0( parent )
Widget parent;
{
	Display *display = XtDisplay ( parent );
	Widget children[18];      /* Children to manage */
	Arg al[64];           /* Arg List */
	register int ac = 0;      /* Arg Count */
	char from_s [256];    /* For font list conversion */
	XrmValue from_value, to_value; /* ditto */
	int fg, bg;           /* colour values for pixmaps */ 
	XmString *list_items; /* For list items */
	int list_item;        /* Index for list_items */
	XmString xmstrings[15];    /* temporary storage for XmStrings */
	Widget widget0;
	Widget widget1;
	Widget widget2;
	Widget widget4;
	Widget widget5;
	Widget widget6;
	Widget widget7;
	Widget widget8;
	Widget widget9;
	Widget widget10;
	Widget widget11;
	Widget widget12;
	Widget widget13;
	Widget widget14;
	Widget widget15;
	Widget widget16;
	Widget widget17;
	Widget widget18;
	Widget widget19;
	Widget widget20;
	Widget widget21;
	Widget widget22;
	Widget widget23;
	Widget widget24;
	Widget widget25;
	Widget widget26;
	Widget widget27;
	Widget widget28;
	Widget widget29;
	Widget widget30;
	Widget widget31;
	Widget widget32;
	Widget widget33;
	Widget widget34;
	Widget widget37;
	Widget widget38;
	Widget widget39;
	Widget widget40;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	widget0 = XmCreateDialogShell ( parent, "dialog", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	widget1 = XmCreateForm ( widget0, "targetDialog", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
	XtSetArg(al[ac], XmNpacking, XmPACK_COLUMN); ac++;
	XtSetArg(al[ac], XmNentryAlignment, XmALIGNMENT_CENTER); ac++;
	XtSetArg(al[ac], XmNadjustLast, FALSE); ac++;
	XtSetArg(al[ac], XmNisAligned, TRUE); ac++;
	widget2 = XmCreateRowColumn ( widget1, "row", al, ac );
	ac = 0;
	button1 = XmCreatePushButton ( widget2, "button1", al, ac );
	widget4 = XmCreatePushButton ( widget2, "button2", al, ac );
	XtSetArg(al[ac], XmNmappedWhenManaged, FALSE); ac++;
	widget5 = XmCreatePushButton ( widget2, "separator_button", al, ac );
	ac = 0;
	widget6 = XmCreatePushButton ( widget2, "button3", al, ac );
	widget7 = XmCreateSeparator ( widget1, "widget7", al, ac );
	XtSetArg(al[ac], XmNlabelType, XmPIXMAP); ac++;
	widget8 = XmCreateLabel ( widget1, "dbox-question", al, ac );
	ac = 0;
	widget9 = XmCreateLabel ( widget1, "optionsLabel", al, ac );
	widget10 = XmCreateLabel ( widget1, "errorLabel", al, ac );
	widget11 = XmCreateFrame ( widget1, "widget11", al, ac );
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	widget12 = XmCreateRadioBox ( widget11, "errorBox", al, ac );
	ac = 0;
	widget13 = XmCreateToggleButtonGadget ( widget12, "errorContinue", al, ac );
	widget14 = XmCreateToggleButtonGadget ( widget12, "errorStop", al, ac );
	widget15 = XmCreateLabel ( widget1, "compileLabel", al, ac );
	widget16 = XmCreateFrame ( widget1, "widget16", al, ac );
	XtSetArg(al[ac], XmNnumColumns, 1); ac++;
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	widget17 = XmCreateRadioBox ( widget16, "compileBox", al, ac );
	ac = 0;
	widget18 = XmCreateToggleButtonGadget ( widget17, "compileFull", al, ac );
	widget19 = XmCreateToggleButtonGadget ( widget17, "compileIncremental", al, ac );
	widget20 = XmCreateToggleButtonGadget ( widget17, "compileNo", al, ac );
	widget21 = XmCreateLabel ( widget1, "linkLabel", al, ac );
	widget22 = XmCreateFrame ( widget1, "widget22", al, ac );
	XtSetArg(al[ac], XmNnumColumns, 1); ac++;
	XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
	widget23 = XmCreateRadioBox ( widget22, "linkBox", al, ac );
	ac = 0;
	widget24 = XmCreateToggleButtonGadget ( widget23, "linkFull", al, ac );
	widget25 = XmCreateToggleButtonGadget ( widget23, "linkIncremental", al, ac );
	widget26 = XmCreateToggleButtonGadget ( widget23, "linkNo", al, ac );
	widget27 = XmCreateLabel ( widget1, "subTargetLabel", al, ac );
	widget28 = XmCreateFrame ( widget1, "widget28", al, ac );
	widget29 = XmCreateRadioBox ( widget28, "subTargetBox", al, ac );
	widget30 = XmCreateToggleButtonGadget ( widget29, "subTargetAll", al, ac );
	widget31 = XmCreateToggleButtonGadget ( widget29, "subTargetNone", al, ac );
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
	widget32 = XmCreateLabel ( widget1, "message", al, ac );
	ac = 0;
	widget33 = XmCreateLabel ( widget1, "buildCommandLabel", al, ac );
	XtSetArg(al[ac], XmNcolumns, 57); ac++;
	XtSetArg(al[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
	XtSetArg(al[ac], XmNrows, 8); ac++;
	widget37 = XmCreateScrolledText ( widget1, "widget37", al, ac );
	ac = 0;
	widget34 = XtParent ( widget37 );

	widget38 = XmCreateLabel ( widget1, "dependLabel", al, ac );
	XtSetArg(al[ac], XmNcolumns, 60); ac++;
	widget39 = XmCreateTextField ( widget1, "dependText", al, ac );
	ac = 0;
	widget40 = XmCreateLabel ( widget1, "iconSeparator", al, ac );
	XtSetArg(al[ac], XmNdefaultButton, button1); ac++;
	XtSetValues ( widget1,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget2,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget2); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 0); ac++;
        XtSetValues ( widget7,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget8,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget15); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget9,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -4); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget11); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget11); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget10,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget28); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget28); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget11,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -4); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget16); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget16); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget15,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget7); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 26); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget16,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -4); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget22); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget22); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget21,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget16); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget16); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget22,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -4); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget28); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget28); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget27,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget22); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget22); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget28,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget38); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget8); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget32,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget34); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget33,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget9); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 26); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget34,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget39); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget38,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget33); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 26); ac++;
	XtSetArg(al[ac], XmNleftWidget, widget40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 13); ac++;
        XtSetValues ( widget39,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 13); ac++;
	XtSetArg(al[ac], XmNtopWidget, widget8); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 13); ac++;
	XtSetArg(al[ac], XmNbottomWidget, widget7); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 13); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
        XtSetValues ( widget40,al, ac );
	ac = 0;
	children[ac++] = button1;
	children[ac++] = widget4;
	children[ac++] = widget5;
	children[ac++] = widget6;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget13;
	children[ac++] = widget14;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget12;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget18;
	children[ac++] = widget19;
	children[ac++] = widget20;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget17;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget24;
	children[ac++] = widget25;
	children[ac++] = widget26;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget23;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget30;
	children[ac++] = widget31;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = widget29;
	XtManageChildren(children, ac);
	ac = 0;
	XtManageChild(widget37);
	children[ac++] = widget2;
	children[ac++] = widget7;
	children[ac++] = widget8;
	children[ac++] = widget9;
	children[ac++] = widget10;
	children[ac++] = widget11;
	children[ac++] = widget15;
	children[ac++] = widget16;
	children[ac++] = widget21;
	children[ac++] = widget22;
	children[ac++] = widget27;
	children[ac++] = widget28;
	children[ac++] = widget32;
	children[ac++] = widget33;
	children[ac++] = widget38;
	children[ac++] = widget39;
	children[ac++] = widget40;
	XtManageChildren(children, ac);
	ac = 0;
}


