/*
This file is automatically generated by xtfunc.el, for inclusion into
xtfunc.c.  Don't touch!  Any modifications you make will get wiped out
the next time xtfunc.el is run on the same input file.
*/

  xxxx_resource_spec_Core[0].lisp_name = intern ("accelerators");
  xxxx_resource_spec_Core[0].lisp_class = Qnil;
  xxxx_resource_spec_Core[1].lisp_name = intern ("ancestor-sensitive");
  xxxx_resource_spec_Core[1].lisp_class = Qnil;
  xxxx_resource_spec_Core[2].lisp_name = intern ("background");
  xxxx_resource_spec_Core[2].lisp_class = Qnil;
  xxxx_resource_spec_Core[3].lisp_name = intern ("background-pixmap");
  xxxx_resource_spec_Core[3].lisp_class = Qnil;
  xxxx_resource_spec_Core[4].lisp_name = intern ("border-color");
  xxxx_resource_spec_Core[4].lisp_class = Qnil;
  xxxx_resource_spec_Core[5].lisp_name = intern ("border-pixmap");
  xxxx_resource_spec_Core[5].lisp_class = Qnil;
  xxxx_resource_spec_Core[6].lisp_name = intern ("border-width");
  xxxx_resource_spec_Core[6].lisp_class = Qnil;
  xxxx_resource_spec_Core[7].lisp_name = intern ("colormap");
  xxxx_resource_spec_Core[7].lisp_class = Qnil;
  xxxx_enum_spec_9[0].lisp = intern("zero");
  xxxx_enum_spec_9[1].lisp = intern("eins");
  xxxx_enum_spec_9[2].lisp = intern("zwei");
  xxxx_enum_spec_9[3].lisp = intern("vier");
  xxxx_enum_spec_9[4].lisp = intern("sieben");
  xxxx_enum_spec_9[5].lisp = intern("acht");
  xxxx_enum_spec_9[6].lisp = intern("elf");
  xxxx_enum_spec_9[7].lisp = intern("neunzehn");
  xxxx_enum_spec_9[8].lisp = intern("dreiundachtzig");
  xxxx_enum_spec_9[9].lisp = intern("vingt-et-un");

  xxxx_resource_spec_Core[8].lisp_name = intern ("depth");
  xxxx_resource_spec_Core[8].lisp_class = Qnil;
  xxxx_resource_spec_Core[9].lisp_name = intern ("destroy-callback");
  xxxx_resource_spec_Core[9].lisp_class = Qnil;
  xxxx_resource_spec_Core[10].lisp_name = intern ("height");
  xxxx_resource_spec_Core[10].lisp_class = Qnil;
  xxxx_resource_spec_Core[11].lisp_name = intern ("initial-resources-persistent");
  xxxx_resource_spec_Core[11].lisp_class = Qnil;
  xxxx_resource_spec_Core[12].lisp_name = intern ("mapped-when-managed");
  xxxx_resource_spec_Core[12].lisp_class = Qnil;
  xxxx_resource_spec_Core[13].lisp_name = intern ("screen");
  xxxx_resource_spec_Core[13].lisp_class = Qnil;
  xxxx_resource_spec_Core[14].lisp_name = intern ("sensitive");
  xxxx_resource_spec_Core[14].lisp_class = Qnil;
  xxxx_resource_spec_Core[15].lisp_name = intern ("translations");
  xxxx_resource_spec_Core[15].lisp_class = Qnil;
  xxxx_resource_spec_Core[16].lisp_name = intern ("width");
  xxxx_resource_spec_Core[16].lisp_class = Qnil;
  xxxx_resource_spec_Core[17].lisp_name = intern ("x");
  xxxx_resource_spec_Core[17].lisp_class = Qnil;
  xxxx_resource_spec_Core[18].lisp_name = intern ("y");
  xxxx_resource_spec_Core[18].lisp_class = Qnil;

  QCore = intern("core");
  Fset (QCore, classobj = make_widget_class (Qnil, QCore, coreWidgetClass, 19, xxxx_resource_spec_Core));
  xxxx_class_Core = XWIDGET_CLASS (classobj);

