/*
This file is automatically generated by xtfunc.el, for inclusion into
xtfunc.c.  Don't touch!  Any modifications you make will get wiped out
the next time xtfunc.el is run on the same input file.
*/

static Lisp_Object QCore;
struct Lisp_Widget_Class *xxxx_class_Core;

xtf_type_class xxxx_type_class_boolean = { L2C_boolean, C2L_boolean, NULL, "boolean", {0}};
xtf_type_class xxxx_type_class_enum = { L2C_enum, C2L_enum, NULL, "enum", {0}};
xtf_type_class xxxx_type_class_int = { L2C_int, C2L_int, NULL, "int", {0}};
xtf_type_class xxxx_type_class_none = { NULL, NULL, NULL, "none", {0}};
xtf_type_class xxxx_type_class_short = { L2C_short, C2L_short, NULL, "short", {0}};
xtf_type_class xxxx_type_class_unsigned_int = { L2C_unsigned_int, C2L_unsigned_int, NULL, "unsigned_int", {0}};
xtf_type_class xxxx_type_class_unsigned_short = { L2C_unsigned_short, C2L_unsigned_short, NULL, "unsigned_short", {0}};
xtf_type_class xxxx_type_class_pixel = { L2C_pixel, C2L_pixel, stage2_pixel, "pixel", {1}};
xtf_type_class xxxx_type_class_pixmap = { L2C_pixmap, C2L_pixmap, stage2_pixmap, "pixmap", {1}};
xtf_type xxxx_type_0 = {&xxxx_type_class_none, 0};
xtf_type xxxx_type_1 = {&xxxx_type_class_boolean, 0};
xtf_type xxxx_type_2 = {&xxxx_type_class_pixel, 0};
xtf_type xxxx_type_3 = {&xxxx_type_class_pixmap, 0};
xtf_type xxxx_type_4 = {&xxxx_type_class_pixel, 0};
xtf_type xxxx_type_5 = {&xxxx_type_class_pixmap, 0};
xtf_type xxxx_type_6 = {&xxxx_type_class_unsigned_short, 0};
xtf_type xxxx_type_7 = {&xxxx_type_class_none, 0};
xtf_enum_spec xxxx_enum_spec_9[] = {
  {0, XmZERO},
  {0, XmEINS},
  {0, XmZWEI},
  {0, XmVIER},
  {0, XmSIEBEN},
  {0, XmACHT},
  {0, XmELF},
  {0, XmNEUNZEHN},
  {0, XmDREIUNDACHTZIG},
  {0, XmVINGT_ET_UN},
};

xtf_enum xxxx_enum_9 = { 10, xxxx_enum_spec_9 };

xtf_type xxxx_type_8 = {&xxxx_type_class_enum, &xxxx_enum_9};
xtf_type xxxx_type_10 = {&xxxx_type_class_none, 0};
xtf_type xxxx_type_11 = {&xxxx_type_class_unsigned_short, 0};
xtf_type xxxx_type_12 = {&xxxx_type_class_boolean, 0};
xtf_type xxxx_type_13 = {&xxxx_type_class_boolean, 0};
xtf_type xxxx_type_14 = {&xxxx_type_class_none, 0};
xtf_type xxxx_type_15 = {&xxxx_type_class_boolean, 0};
xtf_type xxxx_type_16 = {&xxxx_type_class_none, 0};
xtf_type xxxx_type_17 = {&xxxx_type_class_unsigned_short, 0};
xtf_type xxxx_type_18 = {&xxxx_type_class_short, 0};
xtf_type xxxx_type_19 = {&xxxx_type_class_short, 0};
xtf_resource_spec xxxx_resource_spec_Core[] = {
  { NULL, NULL, "accelerators", "Accelerators", &xxxx_type_0, access_create|access_set|access_get },
  { NULL, NULL, "ancestorSensitive", "Sensitive", &xxxx_type_1, access_get },
  { NULL, NULL, "background", "Background", &xxxx_type_2, access_create|access_set|access_get },
  { NULL, NULL, "backgroundPixmap", "Pixmap", &xxxx_type_3, access_create|access_set|access_get },
  { NULL, NULL, "borderColor", "BorderColor", &xxxx_type_4, access_create|access_set|access_get },
  { NULL, NULL, "borderPixmap", "Pixmap", &xxxx_type_5, access_create|access_set|access_get },
  { NULL, NULL, "borderWidth", "BorderWidth", &xxxx_type_6, access_create|access_set|access_get },
  { NULL, NULL, "colormap", "Colormap", &xxxx_type_7, access_create|access_get },
  { NULL, NULL, "depth", "Depth", &xxxx_type_8, access_create|access_set|access_get },
  { NULL, NULL, "destroyCallback", "Callback", &xxxx_type_10, access_create },
  { NULL, NULL, "height", "Height", &xxxx_type_11, access_create|access_set|access_get },
  { NULL, NULL, "initialResourcesPersistent", "InitialResourcesPersistent", &xxxx_type_12, access_create },
  { NULL, NULL, "mappedWhenManaged", "MappedWhenManaged", &xxxx_type_13, access_create|access_set|access_get },
  { NULL, NULL, "screen", "Screen", &xxxx_type_14, access_create|access_get },
  { NULL, NULL, "sensitive", "Sensitive", &xxxx_type_15, access_create|access_set|access_get },
  { NULL, NULL, "translations", "Translations", &xxxx_type_16, access_create|access_set|access_get },
  { NULL, NULL, "width", "Width", &xxxx_type_17, access_create|access_set|access_get },
  { NULL, NULL, "x", "Position", &xxxx_type_18, access_create|access_set|access_get },
  { NULL, NULL, "y", "Position", &xxxx_type_19, access_create|access_set|access_get },
};

